### ISSUE TITLE
Why don't allow ordering on multiple fields?

### ISSUE THREAD

**Issue by fabiocaccamo** [iambrandontaylor/django-admin-sortable#133]
I think it could be useful having the support for something like:
`ordering = ['the_order', '-date']`

In this way if a custom order is not specified we can choose the fallback fields.
The only important thing is that the custom ordering field is the first one.

**Comment by alsoicode** [comment]
Hmm. That's an interesting proposition. Let me mull on that a bit, but thank you for the suggestion.

**Comment by alsoicode** [comment]
I've given this some thought, and it really doesn't make very much sense to me.

There's really no way to determine if an object has a "custom" order at the adminsortable admin class level. Sorting the objects is determined by a positive integer. As such the methods that affect the order would fail if the specified field isn't an integer.

There's nothing special about the position of `ordering` values that could be used to determine if that is the "custom" ordering. it's just another field.

You can always override the ordering of objects at the queryset level regardless of the order specified on the model, which is really the best option I can see, since ordering fields don't override the previous value.

Example:

    class Person(models.Model):

        fn = models.CharField(max_length=50)
        ln = models.CharField(max_length=50)

        class Meta:
            ordering = ['ln', 'fn']

will instruct the class to order objects by the last name, ascending AND the first name ascending, not first name if it comes after the last name.

So specifying a class with an ordering of `['the_order', '-date']` would sort by the order, and the date, which is not what I think you're expecting to happen.
