### ISSUE TITLE
SortableTabularInline styling off

### ISSUE THREAD

**Issue by julianandrews** [iambrandontaylor/django-admin-sortable#145]
The title for inline items overlaps the first field when using a SortableTabularInline. See the attached screen shot. My admin setup looks something like this:

~~~
class MyInline(SortableTabularInline):
    model = MyInlineModel

class MyAdmin(SortableAdmin):
   model = MyModel
   inlines = [MyInline]
~~~

![adminsortable_styling_issue](https://cloud.githubusercontent.com/assets/607449/16243874/86c68b4c-37b6-11e6-8a84-906fc699ae0e.png)

**Comment by alsoicode** [comment]
Hi. Which version of Django? I'm assuming 1.9?

**Comment by julianandrews** [comment]
@alsoicode Yup, 1.9. It may be a 1.9 specific problem. I should have mentioned that!

**Comment by vstoykov** [comment]
I encountered the same problem in 1.8 also

![django-admin-sortable-misplased-icons](https://cloud.githubusercontent.com/assets/902381/16336411/f518c7d4-3a15-11e6-9409-c2c119128427.png)

**Comment by vstoykov** [comment]
I prepared a PR which will make the placement of this icons consistent.
@julianandrews you can test the code from #149 to see if it is ok.

@alsoicode In my PR I changed where the icons will be placed and not trying to fix this exact issue by trying to place the icon in where it was before. I don't know why It is broken because on the sample project it looks ok but in the project that I work on and also in the project where @julianandrews  is working for some strange reason icons are not placed where you want.

In my PR I make them inline with the header of the row (both for tabular and stacked inlines) in order for placement of the icons to be consistent. I hope that you will like the new position of the icons. In the PR there are screenshots how it will look with the changes.

**Comment by julianandrews** [comment]
@vstoykov Thanks for the fix, this worked for me too!
