### ISSUE TITLE
Uncaught error when using `SortableAdminBase` in admin view

### ISSUE THREAD

**Issue by herrbenesch** [iambrandontaylor/django-admin-sortable#256]
Hi, thank you for the great package!
we have the following setup in different admin views.

python version == 3.10.3
Django version ==  4.0.4
adminsortable version == 2.0.3

```python
class MyForm(forms.ModelForm):
    pictures = ImageField(
        label=_("Pictures")
    )
    ...

class MyInlineAdmin(SortableInlineAdminMixin, admin.TabularInline):
    model = models.MyPicture
    form = MyPictureAdminForm
    extra = 0
    max_num = 0
    ordering = models.MyPicture._meta.ordering

@admin.register(models.MyModel)
class MyModelAdmin(SomeAdminMixin, SortableAdminBase, admin.ModelAdmin):
    form = MyForm
    inlines = [MyInlineAdmin]
    ...
```

in the file `myapp/myadmin.py`

When visiting the **list view** for the concerned model, e.g. `myserver.com/admin/myapp/mymodel`, we are seeing the following issue (copied from the chrome dev tools):

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new n (adminsortable2.min.0f34a23e4b86.js:1:42739)
    at new ve (adminsortable2.min.0f34a23e4b86.js:1:42850)
    at adminsortable2.min.0f34a23e4b86.js:1:47448
```

adminsortable2.min.js comes with `SortableAdminBase`.

This doesn't seem to break anything for our users, but we still wanted to contribute the issue and hope for some help here.

**Comment by avelosa** [comment]
Seeing the same error.

python version == 3.9.11
Django version == 4.0.4
adminsortable2 version == 2.0.3

It's a little bit more of a pain for us because we have cypress ui automation tests that fail due to the console error.

FWIW I think the django admin list template not having an element with `id="admin_sortable2_config"`. In the JavaScript class `SortableBase` the constructor  does `this.config=JSON.parse(document.getElementById("admin_sortable2_config")` 
and thus the error mentioned above.

**Comment by jrief** [comment]
This is the wrong issue tracker.
As @avelosa mentioned, this error belongs to https://github.com/jrief/django-admin-sortable2/issues/309

**Comment by herrbenesch** [comment]
Closed via https://github.com/jrief/django-admin-sortable2/issues/309
